const Positions = {
  QB: 0,
  RB: 1,
  WR: 2,
  TE: 3,
  K: 4,
};

export const UNIVERSAL_VIG = 1.0623;

export const DataPoints = {
  AnyTD: 0,
  RushYds: 1,
  RecYds: 2,
  Recs: 3,
  PassTD: 4,
  PassYds: 5,
  Ints: 6,
};

export const slotcodes = {
  0: "QB", // Quarterback
  2: "RB", // Running Back
  4: "WR", // Wide Receiver
  16: "DST", // Defense/Special Teams
  6: "TE",
  23: "FLEX",
  17: "K",
  20: "BENCH",

  // Add more mappings as needed based on your specific data structure
};
//skipped amon-ra cuz he was commented out
export const PlayerPosMap = new Map([
  ["Dawson Knox (BUF)", Positions.TE],
  ["Darren Waller (LV)", Positions.TE],
  ["Nick Mullens (MIN)", Positions.QB],
  ["Joshua Palmer (LAC)", Positions.WR],
  ["Joe Flacco (NYJ)", Positions.QB],
  ["Jake Browning (CIN)", Positions.QB],
  ["Desmond Ridder (ATL)", Positions.QB],
  ["Isaiah Likely (BAL)", Positions.TE],
  ["Tee Higgins (CIN)", Positions.WR],
  ["Dallas Goedert (PHI)", Positions.TE],
  ["Josh Allen (BUF)", Positions.QB],
  ["Lamar Jackson (BAL)", Positions.QB],
  ["Justin Herbert (LAC)", Positions.QB],
  ["Sam Howell (WAS)", Positions.QB],
  ["Geno Smith (SEA)", Positions.QB],
  ["Trevor Lawrence (JAC)", Positions.QB],
  ["Joe Burrow (CIN)", Positions.QB],
  ["Dak Prescott (DAL)", Positions.QB],
  ["Jared Goff (DET)", Positions.QB],
  ["Brock Purdy (SF)", Positions.QB],
  ["Baker Mayfield (CAR)", Positions.QB],
  ["Kyler Murray (ARI)", Positions.QB],
  ["Jordan Love (GB)", Positions.QB],
  ["Christian McCaffrey (CAR)", Positions.RB],
  ["Will Levis (KC)", Positions.QB],
  ["CJ Stroud (HOU)", Positions.QB],
  ["Zach Wilson (NYJ)", Positions.QB],
  ["Taylor Heinicke (WAS)", Positions.QB],
  ["Mac Jones (NE)", Positions.QB],
  ["Stefon Diggs (BUF)", Positions.WR],
  ["Gardner Minshew II (PHI)", Positions.QB],
  ["Kenny Pickett (PIT)", Positions.QB],
  ["Austin Ekeler (LAC)", Positions.RB],
  ["Aidan O'Connell (KC)", Positions.QB],
  ["Keenan Allen (LAC)", Positions.WR],
  ["Tony Pollard (DAL)", Positions.RB],
  ["CeeDee Lamb (DAL)", Positions.WR],
  ["Jonathan Taylor (IND)", Positions.RB],
  ["Breece Hall (NYJ)", Positions.RB],
  ["Saquon Barkley (NYG)", Positions.RB],
  ["Rachaad White (TB)", Positions.RB],
  ["Aaron Jones (GB)", Positions.RB],
  ["Josh Jacobs (LV)", Positions.RB],
  ["Garrett Wilson (NYJ)", Positions.WR],
  ["Michael Pittman (IND)", Positions.WR],
  ["Rhamondre Stevenson (NE)", Positions.RB],
  ["Alvin Kamara (NO)", Positions.RB],
  ["Derrick Henry (TEN)", Positions.RB],
  ["Deshaun Watson (CLE)", Positions.QB],
  ["James Cook (BUF)", Positions.RB],
  ["Kenneth Walker III (SEA)", Positions.RB],
  ["Terry McLaurin (WAS)", Positions.WR],
  ["Tyler Lockett (SEA)", Positions.WR],
  ["Brandon Aiyuk (SF)", Positions.WR],
  ["Diontae Johnson (PIT)", Positions.WR],
  ["DeAndre Hopkins (ARI)", Positions.WR],
  ["Mike Evans (TB)", Positions.WR],
  ["Travis Etienne Jr (JAC)", Positions.RB],
  ["Najee Harris (PIT)", Positions.RB],
  ["Chris Godwin (TB)", Positions.WR],
  ["Deebo Samuel (SF)", Positions.WR],
  ["Dalton Kincaid (BUF)", Positions.TE],
  ["Calvin Ridley (JAC)", Positions.WR],
  ["Jahmyr Gibbs (DET)", Positions.RB],
  ["David Montgomery (DET)", Positions.RB],
  ["Javonte Williams (DEN)", Positions.RB],
  ["Christian Kirk (JAC)", Positions.WR],
  ["Bijan Robinson (WAS)", Positions.RB],
  ["DK Metcalf (SEA)", Positions.WR],
  ["Jaylen Warren (PIT)", Positions.RB],
  ["Tommy DeVito (NYJ)", Positions.QB],
  ["Evan Engram (JAC)", Positions.TE],
  ["Mark Andrews (BAL)", Positions.TE],
  ["Sam LaPorta (IND)", Positions.TE],
  ["Amari Cooper (CLE)", Positions.WR],
  ["Demario Douglas (NE)", Positions.WR],
  ["Jerome Ford (CLE)", Positions.RB],
  ["George Pickens (PIT)", Positions.WR],
  ["Zay Flowers (NE)", Positions.WR],
  ["Jahan Dotson (WAS)", Positions.WR],
  ["George Kittle (SF)", Positions.TE],
  ["Davante Adams (LV)", Positions.WR],
  ["Jake Ferguson (DAL)", Positions.TE],
  ["Marquise Brown (ARI)", Positions.WR],
  ["Jaxon Smith-Njigba (SEA)", Positions.WR],
  ["Gus Edwards (BAL)", Positions.RB],
  ["Khalil Shakir (BUF)", Positions.WR],
  ["Christian Watson (GB)", Positions.WR],
  ["Jerry Jeudy (DEN)", Positions.WR],
  ["Romeo Doubs (GB)", Positions.WR],
  ["Joe Mixon (CIN)", Positions.RB],
  ["Brandin Cooks (HOU)", Positions.WR],
  ["Logan Thomas (WAS)", Positions.TE],
  ["Tyjae Spears (TB)", Positions.RB],
  ["Drake London (ATL)", Positions.WR],
  ["Courtland Sutton (DEN)", Positions.WR],
  ["Ezekiel Elliott (DAL)", Positions.RB],
  ["Trey McBride (ARI)", Positions.TE],
  ["Brian Robinson Jr (WAS)", Positions.RB],
  ["David Njoku (CLE)", Positions.TE],
  ["Hunter Henry (NE)", Positions.TE],
  ["Devin Singletary (BUF)", Positions.RB],
  ["Cade Otton (TB)", Positions.TE],
  ["Quentin Johnston (LAC)", Positions.WR],
  ["Jakobi Meyers (NE)", Positions.WR],
  ["Wan'Dale Robinson (NYG)", Positions.WR],
  ["Elijah Moore (NYJ)", Positions.WR],
  ["Zach Charbonnet (SEA)", Positions.RB],
  ["Tank Dell (HOU)", Positions.WR],
  ["Gerald Everett (LAC)", Positions.TE],
  ["Allen Lazard (GB)", Positions.WR],
  ["Josh Reynolds (DET)", Positions.WR],
  ["Kyle Pitts (ATL)", Positions.TE],
  ["Jayden Reed (GB)", Positions.WR],
  ["Michael Wilson (ARI)", Positions.WR],
  ["James Conner (ARI)", Positions.RB],
  ["Gabe Davis (BUF)", Positions.WR],
  ["Tyler Conklin (NYJ)", Positions.TE],
  ["Dalton Schultz (DAL)", Positions.TE],
  ["Zack Moss (IND)", Positions.RB],
  ["Kareem Hunt (CLE)", Positions.RB],
  ["Luke Musgrave (GB)", Positions.TE],
  ["Chig Okonkwo (TEN)", Positions.TE],
  ["Darius Slayton (NYG)", Positions.WR],
  ["Mike Gesicki (MIA)", Positions.TE],
  ["Connor Heyward (PIT)", Positions.TE],
  ["Taysom Hill (NO)", Positions.TE],
  ["Kyle Philips (TEN)", Positions.WR],
  ["Joshua Kelley (LAC)", Positions.RB],
  ["JuJu Smith-Schuster (KC)", Positions.WR],
  ["Odell Beckham Jr (LAR)", Positions.WR],
  ["Nick Westbrook-Ikhine (TEN)", Positions.WR],
  ["Noah Brown (DAL)", Positions.WR],
  ["Joshua Dobbs (CLE)", Positions.QB],
  ["Jonnu Smith (NE)", Positions.TE],
  ["Antonio Gibson (WAS)", Positions.RB],
  ["AJ Dillon (GB)", Positions.RB],
  ["Tyler Allgeier (ATL)", Positions.RB],
  ["Trey Palmer (NE)", Positions.WR],
  ["Jameson Williams (DET)", Positions.WR],
  ["Rico Dowdle (DAL)", Positions.RB],
  ["Jauan Jennings (SF)", Positions.WR],
  ["Rashod Bateman (BAL)", Positions.WR],
  ["Jalen Reagor (MIN)", Positions.WR],
  ["Keaton Mitchell (CLE)", Positions.RB],
  ["Robert Woods (TEN)", Positions.WR],
  ["Jalen Guyton (LAC)", Positions.WR],
  ["Noah Fant (SEA)", Positions.TE],
  ["Travis Etienne (JAC)", Positions.RB],
  ["Daniel Bellinger (NYG)", Positions.TE],
  ["Jalin Hyatt (NYG)", Positions.WR],
  ["Justin Jefferson (MIN)", Positions.WR],
  ["Amon-Ra St Brown (DET)", Positions.WR],
  ["Samaje Perine (CIN)", Positions.RB],
  ["Donald Parham Jr (LAC)", Positions.TE],
  ["Brian Robinson (WAS)", Positions.RB],
  ["Dontayvion Wicks (GB)", Positions.WR],
  ["DK Metcalf (SEA)", Positions.WR],
  ["Alexander Mattison (MIN)", Positions.RB],
  ["Gabriel Davis (BUF)", Positions.WR],
  ["Kalif Raymond (DET)", Positions.WR],
  ["Chris Olave (NO)", Positions.WR],
  ["Jordan Addison (MIN)", Positions.WR],
  ["KJ Osborn (MIN)", Positions.WR],
  ["TJ Hockenson (MIN)", Positions.TE],
  ["Michael Thomas (NO)", Positions.WR],
  ["Jaleel McLaughlin (IND)", Positions.RB],
  ["AJ Dillon (GB)", Positions.RB],
  ["Alec Pierce (IND)", Positions.WR],
  ["Josh Downs (IND)", Positions.WR],
  ["Michael Gallup (DAL)", Positions.WR],
  ["Latavius Murray (DEN)", Positions.RB],
  ["Donald Parham (LAC)", Positions.TE],
  ["Jamal Agnew (JAX)", Positions.WR],
  ["Tank Bigsby (JAX)", Positions.WR],
  ["Zay Jones (JAX)", Positions.WR],
  ["Allen Robinson (PIT)", Positions.WR],
  ["Jamaal Williams (DET)", Positions.RB],
  ["Juwan Johnson (NO)", Positions.TE],
  ["Chris Moore (HOU)", Positions.WR],
  ["Curtis Samuel (WAS)", Positions.WR],
  ["Kylen Granson (IND)", Positions.TE],
  ["Justice Hill (BAL)", Positions.RB],
  ["Odell Beckham (BAL)", Positions.WR],
  ["Jake Bobo (SEA)", Positions.WR],
  ["Rashid Shaheed (NO)", Positions.WR],
  ["Elijah Mitchell (SF)", Positions.RB],
  ["Chigoziem Okonkwo (TEN)", Positions.WR],
  ["Marvin Mims (DEN)", Positions.WR],
  ["Brock Wright (DET)", Positions.TE],
  ["Gardner Minshew (IND)", Positions.QB],
  ["Brandon Powell (MIN)", Positions.WR],
  ["Ty Chandler (MIN)", Positions.RB],
  ["Chase Edmonds (TB)", Positions.RB],
  ["Donovan Peoples-Jones (CLE)", Positions.WR],
  ["Xavier Gipson (NYJ)", Positions.WR],
  ["Michael Mayer (LV)", Positions.TE],
  ["Calvin Austin III (PIT)", Positions.WR],
  ["Jordan Mason (SF)", Positions.RB],
  ["Andrew Ogletree (IND)", Positions.TE],
  ["Isaiah McKenzie (IND)", Positions.RB],
  ["Nelson Agholor (BAL)", Positions.WR],
  ["Foster Moreau (NO)", Positions.TE],
  ["Trishton Jackson (MIN)", Positions.WR],
  ["Antoine Green (DET)", Positions.WR],
  ["Craig Reynolds (DET)", Positions.RB],
  ["Devine Ozigbo (DEN)", Positions.RB],
  ["Jalen Tolbert (DAL)", Positions.WR],
  ["Kavontae Turpin (DAL)", Positions.RB],
  ["Colby Parkinson (SEA)", Positions.TE],
  ["DeeJay Dallas (SEA)", Positions.RB],
  ["Jamison Crowder (WAS)", Positions.WR],
  ["Deonte Harty (BUF)", Positions.WR],
  ["Quintin Morris (BUF)", Positions.TE],
  ["Adam Trautman (DEN)", Positions.TE],
  ["Russell Wilson (DEN)", Positions.QB],
  ["Harrison Bryant (CLE)", Positions.WR],
  ["Tim Jones (JAX)", Positions.WR],
  ["Ray-Ray McCloud (SF)", Positions.WR],
  ["Dalvin Cook (MIN)", Positions.RB],
  ["Michael Carter (NYJ)", Positions.RB],
  ["Josh Oliver (MIN)", Positions.TE],
  ["Ja'Marr Chase (CIN)", Positions.WR],
  ["Tyler Boyd (CIN)", Positions.WR],
  ["Trenton Irwin (CIN)", Positions.WR],
  ["AJ Brown (PHI)", Positions.WR],
  ["DeVonta Smith (PHI)", Positions.WR],
  ["Rashee Rice (KC)", Positions.WR],
  ["Nico Collins (HOU)", Positions.WR],
  ["Mike Boone (HOU)", Positions.RB],
  ["Rondale Moore (ARI)", Positions.WR],
  ["John Metchie III (HOU)", Positions.WR],
  ["CJ Stroud (HOU)", Positions.QB],
  ["Keaontay Ingram (ARI)", Positions.RB],
  ["Xavier Hutchinson (ATL)", Positions.WR],
  ["Brevin Jordan (HOU)", Positions.TE],
  ["Geoff Swaim (TEN)", Positions.TE],
  ["Greg Dortch (ARI)", Positions.WR],
  ["D'Onta Foreman (CHI)", Positions.RB],
  ["Justin Fields (CHI)", Positions.QB],
  ["Khalil Herbert (CHI)", Positions.RB],
  ["DJ Moore (CHI)", Positions.WR],
  ["Cole Kmet (CHI)", Positions.TE],
  ["Roschon Johnson (CHI)", Positions.RB],
  ["Darnell Mooney (CHI)", Positions.WR],
  ["Tyler Scott (CHI)", Positions.DE],
  ["Equanimeous St Brown (CHI)", Positions.WR],
  ["Travis Homer (SEA)", Positions.RB],
  ["Robert Tonyan Jr (GB)", Positions.TE],
  ["Marcedes Lewis (GB)", Positions.TE],
  ["Trent Taylor (CIN)", Positions.WR],
  ["Chuba Hubbard (CAR)", Positions.RB],
  ["Adam Thielen (MIN)", Positions.WR],
  ["Miles Sanders (PHI)", Positions.RB],
  ["DJ Chark (DET)", Positions.WR],
  ["Jonathan Mingo (CIN)", Positions.WR],
  ["Terrace Marshall Jr (CAR)", Positions.WR],
  ["Jalen Brooks (SEA)", Positions.WR],
  ["Bryce Young (CAR)", Positions.QB],
  ["Tommy Tremble (CAR)", Positions.TE],
  ["Luke Schoonmaker (CAR)", Positions.TE],
  ["Peyton Hendershot (DAL)", Positions.TE],
  ["Laviska Shenault Jr (CAR)", Positions.WR],
  ["Hunter Luepke (GB)", Positions.FB],
  ["Sean McKeon (DAL)", Positions.TE],
  ["Ian Thomas (CAR)", Positions.TE],
  ["DJ Chark Jr (DET)", Positions.WR],
  ["Stephen Sullivan (CAR)", Positions.TE],
  ["Tyreek Hill (MIA)", Positions.WR],
  ["Raheem Mostert (MIA)", Positions.RB],
  ["De'Von Achane (MIA)", Positions.RB],
  ["Jaylen Waddle (MIA)", Positions.WR],
  ["Jeff Wilson Jr (MIA)", Positions.RB],
  ["Cedrick Wilson (MIA)", Positions.WR],
  ["Durham Smythe (MIA)", Positions.TE],
  ["Salvon Ahmed (MIA)", Positions.RB],
  ["Tua Tagovailoa (MIA)", Positions.QB],
  ["Braxton Berrios (NYJ)", Positions.WR],
  ["Julian Hill (NYJ)", Positions.WR],
  ["Austin Hooper (TEN)", Positions.TE],
  ["Hunter Renfrow (LV)", Positions.WR],
  ["Alec Ingold (LV)", Positions.FB],
  ["Ameer Abdullah (LV)", Positions.RB],
  ["Deandre Carter (LV)", Positions.WR],
  ["Tre Tucker (LV)", Positions.WR],
  ["Zamir White (LV)", Positions.RB],
  ["Devon Achane (MIA)", Positions.RB],
  ["Derius Davis (LV)", Positions.WR],
  ["Tucker Kraft (LV)", Positions.TE],
  ["Stone Smartt (LV)", Positions.QB],
  ["Malik Heath (LV)", Positions.WR],
  ["Nick Vannett (LV)", Positions.TE],
  ["Simi Fehoko (LV)", Positions.WR],
  ["Josiah Deguara (GB)", Positions.TE],
  ["Matt Breida (NYG)", Positions.RB],
  ["Chris Rodriguez Jr (WAS)", Positions.RB],
  ["Jashaun Corbin (CAR)", Positions.RB],
  ["Dyami Brown (WAS)", Positions.WR],
  ["Isaiah Hodgins (WAS)", Positions.WR],
  ["Byron Pringle (CHI)", Positions.WR],
  ["John Bates (WAS)", Positions.TE],
  ["Sterling Shepard (NYG)", Positions.WR],
  ["Deon Jackson (IND)", Positions.RB],
  ["Lawrence Cager (NYJ)", Positions.WR],
  ["Parris Campbell (IND)", Positions.WR],
  ["Pat Freiermuth (PIT)", Positions.TE],
  ["Dorian Thompson-Robinson (CLE)", Positions.QB],
  ["Cedric Tillman (TEN)", Positions.WR],
  ["David Bell (CLE)", Positions.WR],
  ["Pierre Strong (NE)", Positions.RB],
  ["Miles Boykin (PIT)", Positions.WR],
  ["James Proche (BAL)", Positions.WR],
  ["Darnell Washington (PIT)", Positions.TE],
  ["Jordan Akins (HOU)", Positions.TE],
  ["Elijah Cooks (JAX)", Positions.WR],
  ["Brenton Strange (PIT)", Positions.TE],
  ["Luke Farrell (JAX)", Positions.TE],
  ["Parker Washington (PIT)", Positions.WR],
  ["Josh Whyle (CIN)", Positions.TE],
  ["Trevon Wesco (CHI)", Positions.TE],
  ["Kyle Juszczyk (SF)", Positions.FB],
  ["Deven Thompkins (TB)", Positions.WR],
  ["Ronnie Bell (SF)", Positions.WR],
  ["Rakim Jarrett (TB)", Positions.WR],
  ["Ke'Shawn Vaughn (TB)", Positions.RB],
  ["Ko Kieft (TB)", Positions.TE],
  ["Payne Durham (TB)", Positions.TE],
  ["Israel Abanikanda (NYJ)", Positions.RB],
  ["Malik Taylor (NYJ)", Positions.WR],
  ["Randall Cobb (NYJ)", Positions.WR],
  ["Trent Sherfield (BUF)", Positions.WR],
  ["CJ Uzomah (NYJ)", Positions.TE],
  ["Reggie Gilliam (BUF)", Positions.FB],
  ["Irvin Charles (NYJ)", Positions.WR],
  ["Jeremy Ruckert (NYJ)", Positions.TE],
  ["Cooper Kupp (LAR)", Positions.WR],
  ["Darrell Henderson (JAX)", Positions.RB],
  ["Puka Nacua (LAR)", Positions.WR],
  ["Royce Freeman (LAR)", Positions.RB],
  ["Tutu Atwell (LAR)", Positions.WR],
  ["Tyler Higbee (LAR)", Positions.TE],
  ["Ben Skowronek (LAR)", Positions.WR],
  ["Matthew Stafford (LAR)", Positions.QB],
  ["Will Dissly (SEA)", Positions.TE],
  ["Demarcus Robinson (BAL)", Positions.WR],
  ["Brycen Hopkins (LAR)", Positions.TE],
  ["Davis Allen (LAR)", Positions.TE],
  ["Darrell Henderson Jr (JAX)", Positions.RB],
  ["Kene Nwangwu (MIN)", Positions.RB],
  ["Lil'Jordan Humphrey (DEN)", Positions.WR],
  ["Myles Gaskin (MIN)", Positions.RB],
  ["Jalen Nailor (MIN)", Positions.WR],
  ["Chris Manhertz (DEN)", Positions.TE],
  ["N'Keal Harry (MIN)", Positions.WR],
  ["Johnny Mundt (MIN)", Positions.TE],
  ["KJ Osborn (MIN)", Positions.WR],
  ["Marvin Mims Jr (DEN)", Positions.WR],
  ["Travis Kelce (KC)", Positions.TE],
  ["Isiah Pacheco (KC)", Positions.RB],
  ["Jalen Hurts (PHI)", Positions.QB],
  ["Patrick Mahomes (KC)", Positions.QB],
  ["D'Andre Swift (PHI)", Positions.RB],
  ["Jerick McKinnon (KC)", Positions.RB],
  ["Justin Watson (KC)", Positions.WR],
  ["Kadarius Toney (KC)", Positions.WR],
  ["Marquez Valdes-Scantling (KC)", Positions.WR],
  ["Skyy Moore (KC)", Positions.WR],
  ["Clyde Edwards-Helaire (KC)", Positions.RB],
  ["Mecole Hardman (NYJ)", Positions.WR],
  ["Noah Gray (KC)", Positions.TE],
  ["Kyren Williams (LAR)", Positions.RB],
  ["Gardner Minshew (IND)", Positions.QB],
  ["Derek Carr (NO)", Positions.QB],

  ["Marvin Harrison Jr. (ARI)", Positions.WR],
  ["Malik Nabers (NYG)", Positions.WR],
  ["Jonathon Brooks (CAR)", Positions.RB],
  ["Brock Bowers (LV)", Positions.TE],
  ["Brian Thomas Jr. (JAC)", Positions.WR],
  ["Xavier Worthy (KC)", Positions.WR],
  ["Xavier Legette (CAR)", Positions.WR],
  ["Caleb Williams (CHI)", Positions.QB],
  ["Jayden Daniels (WAS)", Positions.QB],
  ["Ladd McConkey (LAC)", Positions.WR],
  ["Keon Coleman (BUF)", Positions.WR],
  ["Ricky Pearsall (SF)", Positions.WR],
  ["Adonai Mitchell (IND)", Positions.WR],
  ["Trey Benson (ARI)", Positions.RB],
  ["Drake Maye (NE)", Positions.QB],
  ["Ja'Lynn Polk (NE)", Positions.WR],
  ["Jaylen Wright (MIA)", Positions.RB],
  ["MarShawn Lloyd (GB)", Positions.RB],
  ["Jared Wiley (KC)", Positions.TE],
  ["Brenden Rice (LAC)", Positions.WR],
  ["Ainias Smith (PHI)", Positions.WR],
  ["Isaiah Davis (NYJ)", Positions.RB],
  ["Rasheen Ali (BAL)", Positions.RB],
  ["Kimani Vidal (LAC)", Positions.RB],
  ["Johnny Wilson (PHI)", Positions.WR],
  ["Jha'Quan Jackson (TEN)", Positions.WR],
  ["Jawhar Jordan (HOU)", Positions.RB],
  ["Keilan Robinson (JAC)", Positions.RB],
  ["Tre Tucker (LV)", Positions.WR],
  ["Ben Sinnott (WAS)", Positions.TE],
  ["Jalen McMillan (TB)", Positions.WR],
  ["Luke McCaffrey (WAS)", Positions.WR],
  ["Bo Nix (DEN)", Positions.QB],
  ["Blake Corum (LAR)", Positions.RB],
  ["Rome Odunze (CHI)", Positions.WR]


  // need to add chiefs and dolphins players / week 10 byes
]);
