// Prepend the generated-file banner to the library bundle (Vite lib mode
// places rollup banners after its own helpers, and CRA's ESLint needs the
// disable comment first).
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const file = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../odds-react-app/src/tradeOptimizer/engine.js");
const banner = "/* eslint-disable */\n// Generated by trade-optimizer-extension (npm run build:lib). Do not edit by hand.\n";
const src = readFileSync(file, "utf8").replace(/^\/\* eslint-disable \*\/\n\/\/ Generated[^\n]*\n/, "");
writeFileSync(file, banner + src);
console.log("banner added to", path.relative(process.cwd(), file));
