name: Fetch bovada files

on: 
  workflow_dispatch:
  schedule:
    - cron: '30 15,3 * * 1,2,3,4,5,6'
    - cron: '0 8,15 * * 0'
    - cron: '0 15 * * 1,4'
    
jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Calculate Week Number
      id: week
      run: |
        # Create a script to calculate the week number
        echo '
        function getWeekNumber() {
            const startDate = new Date("2024-09-04");
            const currentDate = new Date();
            const diffTime = currentDate - startDate;
            const diffWeeks = Math.floor(diffTime / (1000 * 60 * 60 * 24 * 7));
            const weekNumber = Math.min(Math.max(diffWeeks + 1, 1), 18);
            return weekNumber;
        }
        console.log(getWeekNumber());
        ' > calculateWeek.js
        
        # Run the script and output the week number
        weekNumber=$(node calculateWeek.js)
        echo "weekNumber=$weekNumber" >> $GITHUB_ENV
    - name: generate cookie string
      id: cookieString
      run: |
        # Create a script to calculate the week number
        echo '
        function generateRandomString(length = 160) {
            const characters = "abcdefghijklmnopqrstuvwxyz0123456789";
            let result = "";
            const charactersLength = characters.length;
            
            for (let i = 0; i < length; i++) {
                const randomIndex = Math.floor(Math.random() * charactersLength);
                result += characters[randomIndex];
            }
            
            return result;
        }

        console.log(generateRandomString());
        ' > getCookieString.js
        
        # Run the script and output the week number
        cookieString=$(node getCookieString.js)
        echo "cookieString=$cookieString" >> $GITHUB_ENV

    - name: Generate Filename
      id: filename
      run: |
        # Generate a unique filename based on week number and an incrementing integer
        weekNumber=${{ env.weekNumber }}
        indexFile="BovadaAPIFiles/lastIndex${{ env.weekNumber }}.txt"

        # Retrieve or initialize the index
        if [ -f $indexFile ]; then
          lastIndex=$(cat $indexFile)
          nextIndex=$((lastIndex + 1))
        else
          nextIndex=0
        fi

        # Save the updated index
        echo $nextIndex > $indexFile

        # Construct the filename
        filename="BovadaAPIFiles/2024week${weekNumber}${nextIndex}"
        echo "filename=$filename" >> $GITHUB_ENV

    - name: Fetch JSON from URL
      id: fetch_json
      run: |
        curl -b "variant=v:0|lgn:0|dt:d|os:ns|cntry:CA|cur:USD|jn:0|rt:o|pb:0; AB=variant; TS01890ddd=014b5d5d07${{ env.cookieString }}" -s https://www.bovada.lv/services/sports/event/v2/events/A/description/football/nfl -o ${{ env.filename }}

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: sangactions
        author_email: sangkyun.hanpro@gmail.com
        message: "Update JSON data file in BovadaAPIFiles"
        add: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
