name: Fetch bovada files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Fetch JSON from URL
      id: fetch_json
      run: |
        curl -b "variant=v:0|lgn:0|dt:d|os:ns|cntry:CA|cur:USD|jn:0|rt:o|pb:0; AB=variant; TS01890ddd=014b5d5d07a66650c0240017f9b62f2d4cd17caba0f1d8bac75bfa5c2faa74ca4bfae5c086480ceaefb9eee2ccdf09f20a493b3774b0bbb90746e36c191b65439ba8cc46dca888a2584d37d3f169cde0db3fbddef6" -s https://www.bovada.lv/services/sports/event/v2/events/A/description/football/nfl -o TestBovadaFiles/data.json

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: sangactions
        author_email: sangkyun.hanpro@gmail.com
        message: "Update JSON data file in TestBovadaFiles"
        add: 'TestBovadaFiles/data.json'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        
