name: test Fetch bovada files

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the start of the hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Calculate Week Number
      id: week
      run: |
        # Create a script to calculate the week number
        echo '
        function getWeekNumber() {
            const startDate = new Date("2024-09-04");
            const currentDate = new Date();
            const diffTime = currentDate - startDate;
            const diffWeeks = Math.floor(diffTime / (1000 * 60 * 60 * 24 * 7));
            const weekNumber = Math.min(Math.max(diffWeeks + 1, 1), 18);
            return weekNumber;
        }
        console.log(getWeekNumber());
        ' > calculateWeek.js
        
        # Run the script and output the week number
        weekNumber=$(node calculateWeek.js)
        echo "weekNumber=$weekNumber" >> $GITHUB_ENV
    - name: generate cookie string
      id: cookieString
      run: |
        # Create a script to calculate the week number
        echo '
        function generateRandomString(length = 160) {
            const characters = "abcdefghijklmnopqrstuvwxyz0123456789";
            let result = "";
            const charactersLength = characters.length;
            
            for (let i = 0; i < length; i++) {
                const randomIndex = Math.floor(Math.random() * charactersLength);
                result += characters[randomIndex];
            }
            
            return result;
        }

        console.log(generateRandomString());
        ' > getCookieString.js
        
        # Run the script and output the week number
        cookieString=$(node getCookieString.js)
        echo "cookieString=$cookieString" >> $GITHUB_ENV
    - name: Fetch JSON from URL
      id: fetch_json
      run: |
        curl -b "variant=v:0|lgn:0|dt:d|os:ns|cntry:CA|cur:USD|jn:0|rt:o|pb:0; AB=variant; TS01890ddd=014b5d5d07s1zghzn26tcrzf2bhpgrmsqdvctq6kr0hv5yi1knjjsogisy1ipq4jpbkibskvlfv6iywx5sf6wxj4awstgck33h3qwom0xwcdyh5eza1rz3knmxzllqp45yf41d50xujqxg0gbxjdypuhxa570fskpltwyuszb9" -s https://www.bovada.lv/services/sports/event/v2/events/A/description/football/nfl -o TestBovadaFiles/data2.json

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: sangactions
        author_email: sangkyun.hanpro@gmail.com
        message: "Update JSON data file in TestBovadaFiles"
        add: 'TestBovadaFiles/data.json'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        